### ISSUE TITLE
移至手册中维护？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_custom_symbols#3]
放入图库？

**Comment by seisman** [comment]
符号定义文件需要放在单独的repo中维护。目前这部分内容尚未加到手册里。

**Comment by core-man** [comment]
所以要加吗？

**Comment by seisman** [comment]
要加，但是低优先级。

**Comment by core-man** [comment]
Close since we added it in [绘制 GMT 社区自定义符号](https://docs.gmt-china.org/latest/module/plot/#gmt-custom-symbols)?
