### ISSUE TITLE
发布 v0.1.0?

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_custom_symbols#5]
Originally posted in https://github.com/gmt-china/GMT_docs/pull/356#discussion_r648885388.

**Comment by core-man** [comment]
Ping @seisman for comment?

**Comment by seisman** [comment]
我从来没用过自定义符号，所以也不知道这些符号定义文件究竟是不是对的。

**Comment by core-man** [comment]
我也没用过和制作过自定义符号，[GMT 官方手册](https://docs.generic-mapping-tools.org/latest/cookbook/custom-symbols.html)也未详细描述 *.def* 或者 *.eps* 格式的符号定义文件的制作方法。例如，[city.def](https://github.com/gmt-china/GMT_custom_symbols/blob/master/city.def) 内容是这样的：

```
# Author: Zhaozhiyuan
# Create: 2018-01
# Update:
# Description: Definition file for city symbol. You should give two 
#                    parameters(lontitude,latitude) in inputfile.
# Usage: 
#       This symbol can be used in module 'psxy' with option '-Sk' as :
#                      '-Skcity/1c'
#       or in 'pslegend' as : 
#                      'S 0.2c kcity 0.15i black 0.5p 1c city' 

0	0	1.0	c
0   0   0.4 c  -Gblack
```


如果我们计划正是维护这个仓库，那么确实首先需要解决符号文件制作流程。当前，[中文手册：绘制 GMT 社区自定义符号](https://docs.gmt-china.org/latest/module/plot/#gmt)并未讲述该过程。Ping @zhaozhiyuan1989 for comments，因为这些符号大部分都是赵志远和汪园园制作的。

**Comment by core-man** [comment]
GMT 官方手册列出了很多用户贡献的自定义符号：[Users Symbol Contributions](https://docs.generic-mapping-tools.org/latest/users-contrib-symbols.html#)

**Comment by seisman** [comment]
关于自定义符号，需要做的事情包括：

- [ ] 介绍自定义符号的使用方法，即 **plot -Sk**
- [ ] 介绍 GMT 内置的自定义符号 
- [ ] 介绍 GMT 手册列出的用户自定义符号 [Users Symbol Contributions](https://docs.generic-mapping-tools.org/latest/users-contrib-symbols.html)
- [ ] 介绍 GMT 中文手册提供的自定义符号（即本项目）
- [ ] 介绍用户如何自行定义符号 (即https://docs.generic-mapping-tools.org/latest/cookbook/custom-symbols.html)

这部分内容其实很长，我觉得可以作为单独的一节，但是具体放在哪里我不确定。

**Comment by zhaozhiyuan1989** [comment]
@core-man 我最近在野外做勘探工作，所以回复的可能比较慢。制作自定义符号这一节我个人认为官方手册讲的不是很清楚，而且属于很进阶的用法，一般用户很少会接触到，他们可能更期望我们直接提供所需要的def文件。如果真的打算介绍的话，需要新开一节详细说明。

**Comment by core-man** [comment]
> 制作自定义符号这一节我个人认为官方手册讲的不是很清楚

是的，没有讲细节。

> 而且属于很进阶的用法，一般用户很少会接触到，他们可能更期望我们直接提供所需要的def文件

是的。但是社区提供的数据需要准确性和明确的流程，就像现在正在构建的中国地学数据集一样 https://docs.gmt-china.org/latest/dataset-CN/

> 如果真的打算介绍的话，需要新开一节详细说明。

主要取决于你是否有时间和意愿维护这个仓库，如果有，自然是对有需求的少数用户是好事。我自己没有使用过这些自定义的符号，所以只能协助你维护。

**Comment by zhaozhiyuan1989** [comment]
好的，这个issue应该没有那么迫切，可以指派给我，我有时间了慢慢弄。

**Comment by seisman** [comment]
Ping @zhaozhiyuan1989
